### ISSUE TITLE
CSS设计指南读书笔记（二）

### ISSUE THREAD

**Issue by zhengxiaowai** [zhengxiaowai/Articles#7]
## 盒子模型

一个元素或者也可以叫一个盒子，是由四部分组成

- content
- padding
- border
- margin

它们由内而外分别是 ```content->panding->border->margin``` 

### 盒子的边框

盒子的边框位于 padding 和 margin 之间的分界线叫做 border。

border 有三个相关的属性

- border-width 用于设置宽度。有 thin、medium、thick等文本值，也可以使用除了百分比和负值之外的数值，
-  border-style 用于设置样式。有 none、dotted、dashed、solid、double、groove、ridge、inset和outset等文本值。
- border-color 用于设置颜色。可以使用 RGB、HSL、十六进制、关键字。
- border-radius 

border-width 中的的3个文本值会因为浏览器的不同而不同，border-style 中只有 soild 是 CSS 明确规定的。

### 盒子的内边距

盒子内边距位于 content 和 border 之前的区域。

相关属性有

- padding
- padding-top
- padding-right
- padding-bottom
- padding-left

四个属性都是设置内边距的宽度，可以指定 px、em等。

其中 padding 为可以简写模式，也可以非简写模式

```css
//简写模式，设置上下为10px，左右为5px
p {padding: 10px 5px}
```

```css
//非简写模式，分别设置上右下左内边距（即顺时针）为 1px、2px、3px、4px
p {padding: 1px 2px 3px 4px}
```

### 盒子的外边距

盒子的外边距位于 border 之外。

属性和使用方法和 padding 一模一样 使用 margin 替代 padding 即可。

盒子的外边距在 block 元素中会有叠加发生，inline 元素则不会有。

例如有两个 p 标签

```html
<p id="p1">i am p1</p>
<p id="p2">i am p2</p>
```

使用 CSS 设置他们的 margin

```css
p#p1 {margin: 10px 0px}
p#p2 {margin: 5px 0px}
```

这时 p1 和 p2 之间的距离是较大的那个外边距就是 10px，如果相同，那么就是那个值。

对于 inline 元素则完全不同，就是两个左或者右边距相加。

## 盒子有多大

世界上有两种盒子，一种是设置了 width 和 没有设置 width 的。

对于没有设置 width 的盒子 宽度默认是父元素的宽度。
有设置 width 的盒子，这里设置 width 只是设置了内容的宽度。

对没有 width 的盒子，给他添加左右 padding 和 margin 会使得内容区域变窄，盒子大小不变。
对于有 width 的盒子，添加左右 padding 和 margin 内容区域不变，盒子变大。
